### PR TITLE
Add Python 2 support

### PR DESCRIPTION
**Pull request by JonathonReinhart**
We switched to Python 3 only because of its `datetime.timezone` class. This restores support for Python 2, by trying to use `pytz` for the UTC timezone.

### CODE REVIEW

**Comment by JonathonReinhart** [comment]
@wpostma I cherry-picked your commit which implemented the python3/pytz switcheroo. I had to modify that commit slightly, because you had a previous commit which also made changes that I didn't want to include, and there were conflicts. Let me know what you think, and if you're able to re-test this in your environments, that would be quite helpful!

**Comment by wpostma** [comment]
I'll retest this at work where it's easier to check lots of environments on monday.

What I like about this approach over explicit version checks is that it works and will continue to work if python 2.7.13 (hypothetical future 2.7.x ver) implements sane timezone info support in the base python distro.   Given that projects I love like Mercurial are stuck on python 2 forever (barring a total rewrite) I predict python2 will continue to receive Love and maybe even a Python 2.8 will one day be released, whether Guido wants it to be or not.

**Comment by JonathonReinhart** [comment]
I went ahead and merged this after testing on Python 2 and 3.

@wpostma I plan on applying an MIT license to this software. As I have included your code, do you have any problem with that?

Also, I'd like to add `setup.py` and cut a v1.0.0 release, so if you test, please do so with `master`. Thanks!

**Comment by wpostma** [comment]
License however you like! Thanks for writing this

**Pull request merged**
