### PR TITLE
WIP: Switch to -m uses days instead of seconds, consider support python2.

### PR DESCRIPTION
**Pull request by wpostma**
Not ready to merge. This just shows what I tried to do to get the script to run.  I am not sure if my datetime utc hackery is correct, I'm just trying to get the script to run and delete me some old build 
artifacts.

### CODE REVIEW

**Comment by wpostma** [comment]
As an additional nicety, I think I'll write you the ability to do this:

`./gitlab-artifact-cleanup -m 4d --project user/app
`
I don't really want to calculate what 4 days is in seconds.  Also I don't see why it's useful to ever provide a non-day-week-month value, I think it should not accept -m 30 as that's ambiguous.

**Comment by JonathonReinhart** [comment]
See my comments on your issue #2.

**Comment by JonathonReinhart** [comment]
Regarding the `-m` option, if you run `--help`, you'll see that is already supported (with slightly different semantics).

```
./gitlab-artifact-cleanup -m '4 days' --project user/app
```

**Comment by wpostma** [comment]
I tried your 1-fix-timezone-issue branch, merged it into my master, and zapped my incorrect changes in this little branch.  The code as shown in this PR works for me, and I like it better with days than seconds.

**Comment by wpostma** [comment]
If you want me to try a python2 backwards compatibility I could try that here, but feel free to close this MR, as it looks like the app works fine, unless you agree about the -m being in days instead of seconds.

**Comment by JonathonReinhart** [comment]
Thanks for the feedback.

I know this is a WIP, but can you limit your PRs to address one thing at a time please?

In its current state in master, the script supports things like `-m '4 days'`. I'm not going to merge something that reduces its flexibility, requiring the units to be in days. If you want to extend the existing functionality to detect things like `4d` (not requiring the user to provide a space-separated argument) that's fine; please do so on a separate branch.

As far as Python 2 goes, yes, feel free to do so. (Again, on a separate branch/PR - this one is quite messy).  If you have no objections, I'll merge my #4 first (which goes to Py3 only), and your new branch can start from there to add Py2 support back in.  The way I see that going is:
- Switch shebang line back to `#!/usr/bin/env python`
- See if `datetime.timezone` exists. If so, then we're using Python 3. Cool.
- Try to import `pytz`. If it works, then we're good.
- Otherwise, you're SOL, you need to install `pytz` or run it with Python 3.

**Comment by JonathonReinhart** [comment]
I could also see maybe switching the _default_ for `-m` to days, instead of seconds, but I want to leave the flexibility there for selecting different units.  Seconds or minutes are useful for testing.

**Comment by wpostma** [comment]
Oh I see.    That's nice.   I was blinded by the initial --help output I
saw which showed how to calculate 2 days in seconds. :-)

On Thu, Oct 13, 2016 at 1:42 PM, Jonathon Reinhart <notifications@github.com

**Comment by JonathonReinhart** [comment]
@wpostma Ahh, I see. No - the help output was supposed to be telling you that you can _actually enter_ `'2 days'`, not how to calculate it :smile:.  Perhaps that could be made more clear.

**Comment by wpostma** [comment]
Sorry for the switcheroos and mess.  Closing.

**Comment by wpostma** [comment]
And thanks for the nice tool!   I'm going to try again with python2 compatibility later.

**Comment by saily** [comment]
Could you please test your stuff before your merge it? `dateutil` is actually called `python-dateutil`. I'll send a new PR.

**Comment by wpostma** [comment]
The pip3 install name should have been python-dateutil in the readme?

**Comment by wpostma** [comment]
This MR was NOT merged, but if the other one was, maybe that's a mistake.

**Comment by wpostma** [comment]
My other MR actually contains this readme change and also merges the other unmerged PRs that I needed to work.

https://github.com/JonathonReinhart/gitlab-artifact-cleanup/pull/5/files

**Comment by saily** [comment]
@wpostma sorry, my post should be there: #4.

**Pull request closed without merging**
